name: TogglePrefix
author: Felix Kurz
version: 1.2
main: de.felix_kurz.toggleprefix.main.Main
api-version: 1.18
softdepend: [spark]

commands:
  toggleprefix:
    description: Der Hauptcommand von TogglePrefix